export const UPDATE_DISPLAY_NAME_SUCCESS = 'UPDATE_DISPLAY_NAME_SUCCESS';
export const UPDATE_DISPLAY_NAME_ERROR = 'UPDATE_DISPLAY_NAME_ERROR';

export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_ERROR = 'SIGNOUT_ERROR';

export const FETCH_INITIAL_SUCCESS = 'FETCH_INITIAL_SUCCESS';
export const FETCH_INITIAL_ERROR = 'FETCH_INITIAL_ERROR';
export const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS';
export const ADD_FEED_START = 'ADD_FEED_START';
export const ADD_FEED_ERROR = 'ADD_FEED_ERROR';
export const ADD_PET_SUCCESS = 'ADD_PET_SUCCESS';
export const ADD_PET_ERROR = 'ADD_PET_ERROR';
export const FETCH_FEEDS_BY_DAYS_SUCCESS = 'FETCH_FEEDS_BY_DAYS_SUCCESS';
export const FETCH_FEEDS_BY_DAYS_ERROR = 'FETCH_FEEDS_BY_DAYS_ERROR';
